version: '3.4'
services:
  pg_db:
    container_name: pg_db
    image: postgres:12.16
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=article_db
    ports:
      - '5433:5432'
    networks:
      - network
networks:
  network:
    name: pub_sub_network
    external: true
